default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: taco-bell-api_development

test:
  <<: *default
  database: taco-bell-api_test

production:
  <<: *default
  database: taco-bell-api-production
  url: <%= ENV['DATABASE_URL'] %>
